apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: application3-chart
  namespace: flux-system
spec: 
  chart: charts
  sourceRef:
    kind: GitRepository
    name: application3-repo  # Matches GitRepository
  interval: 5m