apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml 
  - ./application-1/gitrepository.yaml
  - ./application-1/imagerepository.yaml
  - ./application-1/imagepolicy.yaml
  - ./application-1/helmrelease.yaml
  - ./application-1/helmchart.yaml
  - ./application-1/imageupdateautomation.yaml